import React, { useState, useEffect, useMemo, useRef, useCallback, Suspense, lazy } from 'react';
import axios from 'axios';
import { useLocation, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import {
  Box,
  Typography,
  Paper,
  Button,
  IconButton,
  CircularProgress,
  Alert,
  Avatar,
  Grid,
  Tooltip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Chip,
  MenuItem,
  Select,
  Divider,
} from '@mui/material';
import {
  ProfileCompletionTooltipContent,
  getCompletionChipColor,
} from '../profile/ProfileCompletion';
import LoginSecuritySection from '../profile/LoginSecuritySection';
import PersonIcon from '@mui/icons-material/Person';
import PsychologyIcon from '@mui/icons-material/Psychology';
import WorkHistoryIcon from '@mui/icons-material/WorkHistory';
import DescriptionIcon from '@mui/icons-material/Description';
import EditIcon from '@mui/icons-material/Edit';
import LockIcon from '@mui/icons-material/Lock';
import PuzzlePieceIcon from '@mui/icons-material/Extension';
import AssessmentIcon from '@mui/icons-material/Assessment';
import AccountTreeIcon from '@mui/icons-material/AccountTree';
import AddIcon from '@mui/icons-material/Add';
import DeleteIcon from '@mui/icons-material/Delete';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import { Save as SaveIcon, Cancel as CancelIcon } from '@mui/icons-material';
import UserIdentityTextForm from '../profile/UserIdentityTextForm';
import SeniorityForm from '../profile/SeniorityForm';
import ProfilePictureEditor from '../profile/ProfilePictureEditor';
import ProfileDocumentList from '../profile/ProfileDocumentList';
import ProfilePageActionBar from '../profile/ProfilePageActionBar';
import ProfileSnapTarget from '../profile/ProfileSnapTarget';
import { useProfileMobileScrollSnap } from '../../hooks/useProfileMobileScrollSnap';
import { ProfileMobileSnapContext } from '../../contexts/ProfileMobileSnapContext';
import { buildReviewSaveUserMessage, saveExtractedProfileReview } from '../../utils/profileReviewSaveFlow';
import { clearCvReviewDraft } from '../../utils/cvReviewDraftStorage';

const DocumentUploadForm = lazy(() => import('../profile/DocumentUploadForm'));
import { useAuth } from '../../contexts/AuthContext';
import { USER_IDENTITY_FIELDS } from '../../constants/userIdentityFields';
import { normalizeStructuredListItemLabel } from '../../../constants/structuredListItemLabel';
import { MIN_PROFILE_COMPLETION_REQUIRED } from '../../constants/profileCompletion';
import { hasActiveCareerSimulationSession } from '../../utils/simulationPersistence';
import localizedContentService from '../../utils/localizedContentService';
import { queryClient } from '../../queryClient';
import {
  seedProfileCompletionQueryData,
  profileCompletionQueryKey,
  fetchProfileCompletion,
  getProfileFullQueryKeyFull,
  readFullProfileCacheEntry,
  getProfilePageStateFromCache,
  isReviewSaveProfileSeed,
  fetchFullProfile,
  refreshSeededFullProfileInBackground,
  baseUILanguage,
  PROFILE_QUERY_STALE_TIME_MS,
  PROFILE_QUERY_CACHE_TIME_MS,
  useLastSimulationQuery,
  invalidateFullProfileQuery,
  invalidateProfileCompletionQuery
} from '../../hooks/useProfileQueries';
import { CURRENT_EMPLOYMENT_STATUS_OPTIONS } from '../../../constants/currentEmploymentStatus';
import { HIGHEST_DEGREE_OPTIONS, highestDegreeLabel } from '../../../constants/highestDegree';
import { fireProfileCreatedConfetti } from '../../utils/profileCreatedConfetti';
import { shouldCelebrateProfileSave } from '../../utils/profileSaveCelebration';
import { MOST_SENIOR_OPTIONS } from '../../../constants/senioritySelectOptions';
import { getProfileApiLangQuery } from '../../utils/profileApiLangQuery';
import {
  profileSectionScrollMarginSx,
  scheduleProfileSectionScroll,
  scrollProfileSectionIntoView,
} from '../../utils/profileSectionScroll';

function invalidateProfileCachesAfterMutation() {
  invalidateFullProfileQuery();
  invalidateProfileCompletionQuery();
}

// Internal sentinel generated by backend narratives; keep this value stable for parsing logic.
const WHO_ARE_YOU_PLACEHOLDER = 'No personal profile information available yet.';

function getWhoAreYouNarratives(whoAreYou, lang) {
  const fallback = Array(5).fill('');
  const raw = localizedContentService.getLocalizedWithFallback(whoAreYou?.summary_text, lang, '').trim();
  if (!raw) return fallback;
  const normalizeNarrative = (item) => {
    const text = String(item || '').trim();
    return text === WHO_ARE_YOU_PLACEHOLDER ? '' : text;
  };
  try {
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed) || parsed.length !== 5) return fallback;
    return parsed.map(normalizeNarrative);
  } catch (_err) {
    return fallback;
  }
}

/**
 * Show AI-polished narratives from who_are_you when present; only then fall back to
 * `userIdentity` (raw answers) for empty slots. Preferring raw first hid the narrative layer entirely.
 */
function getWhoAreYouDisplayStrings(whoAreYou, userIdentity, lang) {
  const narratives = getWhoAreYouNarratives(whoAreYou, lang);
  const storedAnswers = Array.isArray(whoAreYou?.raw_answers)
    ? whoAreYou.raw_answers.map((v) => String(v || '').trim())
    : [];
  const identityAnswers = USER_IDENTITY_FIELDS.map(({ key }) => String(userIdentity?.[key] ?? '').trim());
  const answersAligned =
    storedAnswers.length === USER_IDENTITY_FIELDS.length
    && storedAnswers.every((value, idx) => value === identityAnswers[idx]);
  return USER_IDENTITY_FIELDS.map(({ key }, idx) => {
    const n = answersAligned ? String(narratives[idx] ?? '').trim() : '';
    const direct = String(userIdentity?.[key] ?? '').trim();
    return n || direct;
  });
}

const MAX_GOOD_AT_PER_CATEGORY = 10;

/** Chip labels in "What are you good at?" read-only view — match "Who are you?" body text */
const goodAtReadonlyChipSx = (theme) => ({
  height: 'auto',
  '& .MuiChip-label': {
    ...theme.typography.body1,
    whiteSpace: 'normal',
    lineHeight: 1.5,
  },
});

const buildStructuredInfoDraft = ({
  skillDomains = [],
  domains = [],
  keyResponsibilities = [],
  skills = [],
  skillsInDevelopment = [],
} = {}) => ({
  skillDomains: [...skillDomains],
  domains: [...domains],
  keyResponsibilities: [...keyResponsibilities],
  skills: [...skills],
  skillsInDevelopment: [...skillsInDevelopment],
});

const Profile = ({
  showCareerSimulationInputs = true,
  showLoginSecuritySection = true,
}) => {
  const { t, i18n } = useTranslation('onboarding');
  const location = useLocation();
  const navigate = useNavigate();
  const currentLang = baseUILanguage();
  const profileFullKey = useMemo(() => getProfileFullQueryKeyFull(currentLang), [currentLang]);
  const { user, updateUser } = useAuth();
  const initialPageStateRef = useRef(null);
  if (initialPageStateRef.current == null) {
    initialPageStateRef.current = getProfilePageStateFromCache(baseUILanguage());
  }
  const [profile, setProfile] = useState(initialPageStateRef.current.profile);
  const [completion, setCompletion] = useState(initialPageStateRef.current.completion);
  const [loading, setLoading] = useState(initialPageStateRef.current.loading);
  const [error, setError] = useState(null);
  const [editSection, setEditSection] = useState(null);
  const [formLoading, setFormLoading] = useState(false);
  const [formError, setFormError] = useState(null);
  const [editFormData, setEditFormData] = useState({});
  const [editCareerInputs, setEditCareerInputs] = useState(false);
  const [careerInputsDraft, setCareerInputsDraft] = useState(null);
  const [careerInputsLoading, setCareerInputsLoading] = useState(false);
  const [careerInputsError, setCareerInputsError] = useState(null);
  const [chipInputs, setChipInputs] = useState({});
  const [editingChip, setEditingChip] = useState(null);
  const [profilePictureDialogOpen, setProfilePictureDialogOpen] = useState(false);
  const [profilePictureKey, setProfilePictureKey] = useState(0);
  const [loginSecurityDialogOpen, setLoginSecurityDialogOpen] = useState(false);
  const [loginSecurity, setLoginSecurity] = useState({
    data: null,
    loading: true,
    error: null
  });
  const [editStructuredInfo, setEditStructuredInfo] = useState(false);
  const [structuredInfoDraft, setStructuredInfoDraft] = useState(buildStructuredInfoDraft());
  const [structuredInfoLoading, setStructuredInfoLoading] = useState(false);
  const [structuredInfoError, setStructuredInfoError] = useState(null);
  const [profileNameDialogOpen, setProfileNameDialogOpen] = useState(false);
  const [profileNameDraft, setProfileNameDraft] = useState('');
  const [profileNameLoading, setProfileNameLoading] = useState(false);
  const [profileNameError, setProfileNameError] = useState(null);
  const [documentReviewDocId, setDocumentReviewDocId] = useState(null);
  const [savingCvReview, setSavingCvReview] = useState(false);
  const [cvReviewError, setCvReviewError] = useState(null);
  const prevProfileUiLangRef = useRef(null);
  /** Prevents double-fire (Strict Mode) and ties celebration to one history entry. */
  const profileCelebrationHandledKeyRef = useRef(null);
  const userIdentitySectionRef = useRef(null);
  const structuredInfoSectionRef = useRef(null);
  const senioritySectionRef = useRef(null);
  const careerInputsSectionRef = useRef(null);
  const [sectionScrollTarget, setSectionScrollTarget] = useState(null);
  const isProfileReadOnlyView = !editSection && !editStructuredInfo && !editCareerInputs;
  const mobileSnapActive = useProfileMobileScrollSnap(isProfileReadOnlyView);
  const hasSimulationSession = hasActiveCareerSimulationSession();
  const lastSimulationQuery = useLastSimulationQuery({
    enabled:
      !!user &&
      !!completion &&
      Number(completion?.overall || 0) >= MIN_PROFILE_COMPLETION_REQUIRED &&
      !hasSimulationSession
  });
  const goToSimulationHref = useMemo(() => {
    if (hasSimulationSession) return '/simulation/results';
    if (lastSimulationQuery.isError || lastSimulationQuery.data == null) return '/simulation';
    return lastSimulationQuery.data?.results ? '/simulation/results' : '/simulation';
  }, [hasSimulationSession, lastSimulationQuery.data, lastSimulationQuery.isError]);
  const currentEmploymentStatusOptionsByValue = useMemo(
    () => Object.fromEntries(CURRENT_EMPLOYMENT_STATUS_OPTIONS.map((option) => [option.value, option.label])),
    []
  );
  const mostSeniorOptionsByValue = useMemo(
    () => Object.fromEntries(MOST_SENIOR_OPTIONS.map((option) => [option.value, option.label])),
    []
  );
  const getRawItems = (value) => {
    const raw = Array.isArray(value)
      ? value
      : (value && typeof value === 'object' && Array.isArray(value.raw_items) ? value.raw_items : []);
    return raw.map((item) => normalizeStructuredListItemLabel(item, currentLang)).filter(Boolean);
  };
  /** Chips expect a string label; CV overlay / legacy rows may store `{ name }` objects in raw_items. */
  const chipLabelFromGoodAtItem = (item) => normalizeStructuredListItemLabel(item, currentLang);
  const getSummaryText = (value) => {
    if (!value || typeof value !== 'object') return 'No information available yet';
    return localizedContentService.getLocalizedWithFallback(value.summary_text, currentLang, 'No information available yet');
  };
  const formatMostSeniorWorkExperience = (value) => {
    const key = String(value || '').trim();
    if (!key) return '';
    const translated = t(`profilePage.seniorityForm.options.mostSenior.${key}`);
    if (translated && translated !== `profilePage.seniorityForm.options.mostSenior.${key}`) {
      return translated;
    }
    return mostSeniorOptionsByValue[key] || key;
  };

  const formatCurrentEmploymentStatus = (value) => {
    const key = String(value || '').trim();
    if (!key) return '';
    const translated = t(`profilePage.seniorityForm.options.currentStatus.${key}`);
    if (translated && translated !== `profilePage.seniorityForm.options.currentStatus.${key}`) {
      return translated;
    }
    return currentEmploymentStatusOptionsByValue[key] || key;
  };

  const formatHighestDegree = (value) => {
    const key = String(value || '').trim();
    if (!key) return '';
    const translated = t(`profilePage.seniorityForm.options.highestDegree.${key}`);
    if (translated && translated !== `profilePage.seniorityForm.options.highestDegree.${key}`) {
      return translated;
    }
    return highestDegreeLabel(key);
  };

  useEffect(() => {
    const prev = prevProfileUiLangRef.current;
    const langChanged = prev != null && prev !== currentLang;
    prevProfileUiLangRef.current = currentLang;
    fetchProfile({ force: langChanged });
    if (showLoginSecuritySection) {
      fetchLoginSecurity();
    }
  }, [showLoginSecuritySection, currentLang, i18n.language]);

  /** Confetti once after profile creation or full update (ProfileCreation navigate + session fallback). */
  useEffect(() => {
    if (profileCelebrationHandledKeyRef.current === location.key) return;
    if (!shouldCelebrateProfileSave(location.state)) return;

    profileCelebrationHandledKeyRef.current = location.key;
    // Fire synchronously — deferring via rAF races with replace-state navigate cleanup on slower devices.
    fireProfileCreatedConfetti();

    const prev = location.state || {};
    const {
      celebrateProfileSaved: _dropSaved,
      celebrateProfileCreated: _dropCreated,
      ...rest
    } = prev;
    navigate(
      { pathname: location.pathname, search: location.search, hash: location.hash },
      { replace: true, state: Object.keys(rest).length ? rest : undefined }
    );
  }, [location.key, location.pathname, location.search, location.hash, navigate]);

  useEffect(() => {
    if (loginSecurity?.data?.email && loginSecurity.data.email !== user?.email) {
      updateUser({ email: loginSecurity.data.email });
    }
  }, [loginSecurity?.data?.email, user?.email, updateUser]);

  const queueProfileSectionFocus = useCallback((sectionKey) => {
    setSectionScrollTarget(sectionKey);
  }, []);

  useEffect(() => {
    if (!sectionScrollTarget) return undefined;
    scheduleProfileSectionScroll(() => {
      const refBySection = {
        userIdentity: userIdentitySectionRef,
        structuredInfo: structuredInfoSectionRef,
        seniority: senioritySectionRef,
        careerInputs: careerInputsSectionRef,
      };
      scrollProfileSectionIntoView(refBySection[sectionScrollTarget]?.current);
      setSectionScrollTarget(null);
    });
    return undefined;
  }, [sectionScrollTarget, editSection, editStructuredInfo, editCareerInputs]);

  const applyFullProfileToPage = (profileData) => {
    if (!profileData || typeof profileData !== 'object') return;
    setProfile(profileData);
    if (profileData.completion) {
      setCompletion(profileData.completion);
      seedProfileCompletionQueryData({ success: true, completion: profileData.completion });
    }
  };

  /**
   * Loads profile + completion. Uses React Query cache so repeat visits avoid a second
   * full GET /api/profile round-trip (that endpoint is expensive on the server).
   * Use { force: true } after mutations or explicit refresh.
   */
  const fetchProfile = async (options = {}) => {
    const { force = false } = options;
    try {
      setError(null);

      if (!force) {
        const cachedProfile = readFullProfileCacheEntry(currentLang);
        // Do not reuse cache after mutations: invalidateQueries does not refetch inactive queries
        // (this page uses fetchQuery manually, so there is often no active observer).
        if (cachedProfile) {
          setProfile(cachedProfile);
          const cachedCompletionData = queryClient.getQueryData(profileCompletionQueryKey);
          const embeddedCompletion = cachedProfile?.completion || cachedCompletionData?.completion;
          if (embeddedCompletion) {
            setCompletion(embeddedCompletion);
            if (cachedProfile?.completion) {
              seedProfileCompletionQueryData({ success: true, completion: embeddedCompletion });
            }
          }
          setLoading(false);

          const refreshCompletionInBackground = () => {
            if (cachedProfile?.completion) return;
            queryClient
              .prefetchQuery(profileCompletionQueryKey, fetchProfileCompletion, {
                staleTime: PROFILE_QUERY_STALE_TIME_MS,
                cacheTime: PROFILE_QUERY_CACHE_TIME_MS
              })
              .then(() => {
                const latestCompletionData = queryClient.getQueryData(profileCompletionQueryKey);
                if (latestCompletionData?.completion) {
                  setCompletion(latestCompletionData.completion);
                  seedProfileCompletionQueryData(latestCompletionData);
                }
              })
              .catch((completionErr) => {
                console.error('Profile completion refresh failed:', completionErr);
              });
          };

          if (isReviewSaveProfileSeed(cachedProfile)) {
            void refreshSeededFullProfileInBackground(currentLang, {
              onUpdated: applyFullProfileToPage,
            }).catch((profileErr) => {
              console.error('Profile background refresh after review-save failed:', profileErr);
            });
            refreshCompletionInBackground();
            return;
          }

          refreshCompletionInBackground();
          return;
        }
      } else {
        await queryClient.invalidateQueries(profileFullKey);
        await queryClient.invalidateQueries(profileCompletionQueryKey);
      }

      setLoading(true);
      const profileData = await queryClient.fetchQuery(profileFullKey, () => fetchFullProfile(currentLang), {
        staleTime: PROFILE_QUERY_STALE_TIME_MS,
        cacheTime: PROFILE_QUERY_CACHE_TIME_MS
      });
      setProfile(profileData);
      if (profileData?.completion) {
        setCompletion(profileData.completion);
        seedProfileCompletionQueryData({ success: true, completion: profileData.completion });
      } else {
        const completionData = await queryClient.fetchQuery(profileCompletionQueryKey, fetchProfileCompletion, {
          staleTime: PROFILE_QUERY_STALE_TIME_MS,
          cacheTime: PROFILE_QUERY_CACHE_TIME_MS
        });
        setCompletion(completionData.completion);
        seedProfileCompletionQueryData(completionData);
      }
    } catch (err) {
      setError(err.response?.data?.message || t('profilePage.errors.fetchProfileFailed'));
      console.error('Profile fetch error:', err);
    } finally {
      setLoading(false);
    }
  };

  const fetchLoginSecurity = async () => {
    try {
      setLoginSecurity(prev => ({ ...prev, loading: true, error: null }));
      const res = await axios.get('/api/auth/login-security');
      setLoginSecurity({
        data: res.data,
        loading: false,
        error: null
      });
    } catch (err) {
      setLoginSecurity({
        data: null,
        loading: false,
        error: err.response?.data?.error || t('profilePage.loginSecurity.loadFailed')
      });
    }
  };

  const openLoginSecurityDialog = () => {
    setLoginSecurityDialogOpen(true);
    fetchLoginSecurity();
  };

  /**
   * This page manages `completion` locally instead of subscribing with `useProfileCompletionQuery()`.
   * After manual saves, invalidating the query alone leaves the local percentage stale until reload.
   */
  const handleDocumentsUpdate = async (updatedDocs) => {
    setProfile((prev) => ({
      ...prev,
      profile: {
        ...prev.profile,
        documents: updatedDocs,
      },
    }));
    invalidateProfileCachesAfterMutation();
    await refreshCompletionAfterMutation();
  };

  const handleExtractedProfileReview = async (profileData) => {
    setSavingCvReview(true);
    setCvReviewError(null);
    const langQuery = getProfileApiLangQuery();
    const reviewUserId = String(user?.id || user?._id || '').trim();
    try {
      await saveExtractedProfileReview({
        profileData,
        fetchImpl: fetch,
        getAuthToken: () => localStorage.getItem('token'),
        langQuery,
        translate: t,
        prefetchProfile: false,
      });
      if (reviewUserId) clearCvReviewDraft(reviewUserId);
      setDocumentReviewDocId(null);

      const seededProfile = readFullProfileCacheEntry(currentLang);
      if (seededProfile) {
        applyFullProfileToPage(seededProfile);
      }

      void refreshSeededFullProfileInBackground(currentLang, {
        onUpdated: applyFullProfileToPage,
      }).catch((profileErr) => {
        console.error('Profile background refresh after review-save failed:', profileErr);
      });

      if (!seededProfile?.completion) {
        void queryClient
          .prefetchQuery(profileCompletionQueryKey, fetchProfileCompletion, {
            staleTime: PROFILE_QUERY_STALE_TIME_MS,
            cacheTime: PROFILE_QUERY_CACHE_TIME_MS,
          })
          .then(() => {
            const latestCompletionData = queryClient.getQueryData(profileCompletionQueryKey);
            if (latestCompletionData?.completion) {
              setCompletion(latestCompletionData.completion);
              seedProfileCompletionQueryData(latestCompletionData);
            }
          })
          .catch((completionErr) => {
            console.error('Profile completion refresh after CV review save failed:', completionErr);
          });
      }
    } catch (err) {
      setCvReviewError(buildReviewSaveUserMessage(err, t));
      throw err;
    } finally {
      setSavingCvReview(false);
    }
  };

  const refreshCompletionAfterMutation = async () => {
    try {
      const completionData = await queryClient.fetchQuery(profileCompletionQueryKey, fetchProfileCompletion, {
        staleTime: 0,
        cacheTime: PROFILE_QUERY_CACHE_TIME_MS,
      });
      if (completionData?.completion) {
        setCompletion(completionData.completion);
        seedProfileCompletionQueryData(completionData);
      }
    } catch (refreshErr) {
      console.error('Profile completion refresh after mutation failed:', refreshErr);
    }
  };

  const profileCompletionHeader = useMemo(() => {
    if (!completion) return null;
    const pct = completion.overall ?? 0;
    const completionChipSx =
      pct >= 80
        ? {
            bgcolor: 'success.dark',
            color: 'var(--color-on-primary)',
            '& .MuiChip-icon': { color: 'var(--color-on-primary)' },
          }
        : pct >= 50
          ? {
              bgcolor: 'warning.dark',
              color: 'var(--color-on-primary)',
              '& .MuiChip-icon': { color: 'var(--color-on-primary)' },
            }
          : {
              bgcolor: 'error.dark',
              color: 'var(--color-on-primary)',
              '& .MuiChip-icon': { color: 'var(--color-on-primary)' },
            };
    return (
      <Tooltip
        title={<ProfileCompletionTooltipContent completion={completion} />}
        slotProps={{
          tooltip: {
            sx: {
              maxWidth: 400,
              px: 1.75,
              py: 1.25,
            },
          },
        }}
        arrow
        enterDelay={350}
      >
        <Chip
          icon={<AssessmentIcon fontSize="small" />}
          label={`${pct}%`}
          size="small"
          variant="filled"
          color={getCompletionChipColor(pct)}
          sx={{ cursor: 'help', fontWeight: 700, ...completionChipSx }}
        />
      </Tooltip>
    );
  }, [completion]);

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" minHeight="400px">
        <CircularProgress />
      </Box>
    );
  }

  if (error) {
    return (
      <Box sx={{ p: 3 }}>
        <Alert severity="error" sx={{ mb: 2 }}>
          {error}
        </Alert>
        <Button variant="contained" onClick={() => fetchProfile({ force: true })}>
          {t('profilePage.actions.retry')}
        </Button>
      </Box>
    );
  }

  const p = profile?.profile || {};
  const personal = p.personalInfo || {};
  const seniority = p.seniority || {};
  const whoAreYouDisplayLines = getWhoAreYouDisplayStrings(
    p?.who_are_you || {},
    p.userIdentity || {},
    currentLang
  );
  const documents = p.documents || [];
  const structured = p.structuredUserInfo || {};
  const profileDisplayName = (profile?.name || user?.name || '').trim();
  const careerInputsIdentityEmbeddingText = String(
    p?.careerSimulationInputs?.embeddingOptimizedUserIdentityText || ''
  ).trim();

  // Helper for missing/optional fields
  const renderField = (
    label,
    value,
    isOptional = false,
    tooltip = '',
    labelGrid = { xs: 4, sm: 3, md: 2 },
    valueGrid = { xs: 8, sm: 9, md: 10 }
  ) => (
    <Grid container alignItems="center" spacing={1} sx={{ mb: 1 }}>
      <Grid item {...labelGrid}>
        <Typography variant="body1" sx={{ color: '#950202', fontWeight: 600 }}>
          {label}
          {tooltip && (
            <Tooltip title={tooltip}><span style={{ marginLeft: 4, color: 'var(--color-text-hint)' }}>?</span></Tooltip>
          )}
          {isOptional && (
            <Typography component="span" variant="caption" color="text.disabled" sx={{ ml: 1 }}>(optional)</Typography>
          )}
        </Typography>
      </Grid>
      <Grid item {...valueGrid}>
        <Typography variant="body1" color={value ? 'text.primary' : 'text.disabled'}>
          {value || <span style={{ fontStyle: 'italic' }}>{t('profilePage.notProvided')}</span>}
        </Typography>
      </Grid>
    </Grid>
  );

  const structuredSkills = getRawItems(structured.skills);
  const structuredSkillsInDevelopment = getRawItems(structured.skillsInDevelopment);
  const structuredKeyResponsibilities = getRawItems(structured.keyResponsibilities);
  const structuredDomains = getRawItems(structured.domains);
  const structuredSkillDomains = getRawItems(structured.skillDomains);
  /** Overarching strengths: `structuredUserInfo.skillDomains` only (not industry domains). */
  const strengthSkillDomains = structuredSkillDomains;

  const handleEditStructuredInfo = () => {
    setStructuredInfoError(null);
    setStructuredInfoDraft(buildStructuredInfoDraft({
      skillDomains: getRawItems(structured.skillDomains),
      domains: structuredDomains,
      keyResponsibilities: structuredKeyResponsibilities,
      skills: structuredSkills,
      skillsInDevelopment: structuredSkillsInDevelopment,
    }));
    setEditStructuredInfo(true);
    queueProfileSectionFocus('structuredInfo');
  };

  const handleCancelStructuredInfo = () => {
    setEditStructuredInfo(false);
    setStructuredInfoError(null);
  };

  const handleSaveStructuredInfo = async () => {
    setStructuredInfoLoading(true);
    setStructuredInfoError(null);
    try {
      const normalizeList = (items) => {
        const next = [];
        for (const item of items || []) {
          const value = String(item || '').trim();
          if (!value) continue;
          if (next.includes(value)) continue;
          next.push(value);
          if (next.length >= MAX_GOOD_AT_PER_CATEGORY) break;
        }
        return next;
      };
      const payload = {
        skillDomains: normalizeList(structuredInfoDraft.skillDomains),
        skills: normalizeList(structuredInfoDraft.skills),
        skillsInDevelopment: normalizeList(structuredInfoDraft.skillsInDevelopment),
        keyResponsibilities: normalizeList(structuredInfoDraft.keyResponsibilities),
        domains: normalizeList(structuredInfoDraft.domains),
      };
      const res = await axios.put(`/api/profile/structured-user-info?${getProfileApiLangQuery()}`, payload);
      setProfile(prev => {
        const nextStructuredUserInfo = res.data?.structuredUserInfo ?? prev.profile.structuredUserInfo;
        return {
          ...prev,
          profile: {
            ...prev.profile,
            structuredUserInfo: nextStructuredUserInfo,
            careerSimulationInputs: res.data?.careerSimulationInputs ?? prev.profile.careerSimulationInputs
          }
        };
      });
      invalidateProfileCachesAfterMutation();
      await refreshCompletionAfterMutation();
      setEditStructuredInfo(false);
      queueProfileSectionFocus('structuredInfo');
    } catch (err) {
      const data = err.response?.data;
      const msg = data?.message || data?.error || t('profilePage.errors.saveStructuredInfoFailed');
      setStructuredInfoError(msg);
    } finally {
      setStructuredInfoLoading(false);
    }
  };

  const handleStructuredInfoItemChange = (arrayKey, index, value) => {
    setStructuredInfoDraft((prev) => ({
      ...prev,
      [arrayKey]: (prev[arrayKey] || []).map((item, itemIdx) => (
        itemIdx === index ? value : item
      )),
    }));
  };

  const handleStructuredInfoItemAdd = (arrayKey) => {
    setStructuredInfoDraft((prev) => {
      const list = prev[arrayKey] || [];
      if (list.length >= MAX_GOOD_AT_PER_CATEGORY) return prev;
      return { ...prev, [arrayKey]: [...list, ''] };
    });
  };

  const handleStructuredInfoItemRemove = (arrayKey, index) => {
    setStructuredInfoDraft((prev) => ({
      ...prev,
      [arrayKey]: (prev[arrayKey] || []).filter((_, itemIdx) => itemIdx !== index),
    }));
  };

  const handleStartEditProfileName = () => {
    setProfileNameError(null);
    setProfileNameDraft(profileDisplayName);
    setProfileNameDialogOpen(true);
  };

  const handleCancelEditProfileName = () => {
    if (profileNameLoading) return;
    setProfileNameDialogOpen(false);
    setProfileNameError(null);
  };

  const handleSaveProfileName = async () => {
    const trimmedName = profileNameDraft.trim();
    if (!trimmedName) {
      setProfileNameError(t('profilePage.nameEditor.errors.required'));
      return;
    }
    setProfileNameLoading(true);
    setProfileNameError(null);
    try {
      const res = await axios.put(`/api/profile/name?${getProfileApiLangQuery()}`, { name: trimmedName });
      setProfile(prev => ({ ...prev, name: res.data?.name || trimmedName }));
      updateUser({ name: res.data?.name || trimmedName });
      invalidateProfileCachesAfterMutation();
      setProfileNameDialogOpen(false);
    } catch (err) {
      const data = err.response?.data;
      const msg = data?.message || data?.error || t('profilePage.nameEditor.errors.saveFailed');
      setProfileNameError(typeof msg === 'string' ? msg : t('profilePage.nameEditor.errors.saveFailed'));
    } finally {
      setProfileNameLoading(false);
    }
  };

  const handleEditUserIdentity = () => {
    setEditSection('userIdentity');
    setFormError(null);
    const summaryBasedIdentity = USER_IDENTITY_FIELDS.reduce((acc, { key }, idx) => {
      acc[key] = String(whoAreYouDisplayLines[idx] || '').trim();
      return acc;
    }, {});
    setEditFormData(summaryBasedIdentity);
    queueProfileSectionFocus('userIdentity');
  };

  const handleEditSeniority = () => {
    setEditSection('seniority');
    setFormError(null);
    setEditFormData({
      currentStatus: seniority.currentStatus || '',
      yearsOfExperience: seniority.yearsOfExperience,
      highestDegree: seniority.highestDegree || '',
      mostSeniorWorkExperience: seniority.mostSeniorWorkExperience || ''
    });
    queueProfileSectionFocus('seniority');
  };

  const handleCancel = () => {
    setEditSection(null);
    setFormError(null);
  };

  const handleSaveUserIdentity = async (data) => {
    setFormLoading(true);
    setFormError(null);
    try {
      const res = await axios.put(`/api/profile/user-identity?${getProfileApiLangQuery()}`, {
        workEnjoyMost: data.workEnjoyMost,
        topicsIndustriesInterest: data.topicsIndustriesInterest,
        naturallyGoodAt: data.naturallyGoodAt,
        workEnvironmentFit: data.workEnvironmentFit,
        workingLifeAchievement: data.workingLifeAchievement
      });
      setProfile(prev => ({
        ...prev,
        profile: {
          ...prev.profile,
          userIdentity: res.data?.userIdentity ?? prev.profile.userIdentity,
          who_are_you: res.data?.who_are_you ?? prev.profile.who_are_you,
          careerSimulationInputs: res.data?.careerSimulationInputs ?? prev.profile.careerSimulationInputs
        }
      }));
      invalidateProfileCachesAfterMutation();
      await refreshCompletionAfterMutation();
      setEditSection(null);
      queueProfileSectionFocus('userIdentity');
    } catch (err) {
      const responseData = err.response?.data;
      const msg = responseData?.message || responseData?.error || t('profilePage.errors.saveChangesFailed');
      const errStr = typeof msg === 'string' ? msg : (Array.isArray(responseData?.errors) && responseData.errors[0]?.msg) ? responseData.errors[0].msg : t('profilePage.errors.saveChangesFailed');
      setFormError(errStr);
    } finally {
      setFormLoading(false);
    }
  };

  const handleSaveSeniority = async (data) => {
    setFormLoading(true);
    setFormError(null);
    try {
      const res = await axios.put(`/api/profile/seniority?${getProfileApiLangQuery()}`, {
        currentStatus: data.currentStatus,
        yearsOfExperience: data.yearsOfExperience,
        highestDegree: data.highestDegree,
        mostSeniorWorkExperience: data.mostSeniorWorkExperience
      });
      setProfile(prev => ({
        ...prev,
        profile: {
          ...prev.profile,
          seniority: {
            ...prev.profile.seniority,
            ...(res.data?.seniority || {})
          },
          careerSimulationInputs: res.data?.careerSimulationInputs ?? prev.profile.careerSimulationInputs
        }
      }));
      invalidateProfileCachesAfterMutation();
      await refreshCompletionAfterMutation();
      setEditSection(null);
      queueProfileSectionFocus('seniority');
    } catch (err) {
      const responseData = err.response?.data;
      const msg = responseData?.message || responseData?.error || t('profilePage.errors.saveChangesFailed');
      const errStr = typeof msg === 'string' ? msg : (Array.isArray(responseData?.errors) && responseData.errors[0]?.msg) ? responseData.errors[0].msg : t('profilePage.errors.saveChangesFailed');
      setFormError(errStr);
    } finally {
      setFormLoading(false);
    }
  };

  // Handler for editing career simulation inputs (only fields used for user vectors)
  const handleEditCareerInputs = () => {
    setCareerInputsError(null);
    const raw = { ...(profile?.profile?.careerSimulationInputs || {}) };
    const structuredUserInfo = {
      skillDomains: getRawItems(raw.structuredUserInfo?.skillDomains),
      skills: getRawItems(raw.structuredUserInfo?.skills),
      skillsInDevelopment: getRawItems(raw.structuredUserInfo?.skillsInDevelopment),
      keyResponsibilities: getRawItems(raw.structuredUserInfo?.keyResponsibilities),
      domains: getRawItems(raw.structuredUserInfo?.domains)
    };
    const userIdentity = {
      workEnjoyMost: raw.userIdentity?.workEnjoyMost || '',
      topicsIndustriesInterest: raw.userIdentity?.topicsIndustriesInterest || '',
      naturallyGoodAt: raw.userIdentity?.naturallyGoodAt || '',
      workEnvironmentFit: raw.userIdentity?.workEnvironmentFit || '',
      workingLifeAchievement: raw.userIdentity?.workingLifeAchievement || ''
    };
    const seniority = raw.seniority && typeof raw.seniority === 'object' ? raw.seniority : {};
    setCareerInputsDraft({
      structuredUserInfo,
      userIdentity,
      seniority: {
        currentStatus: seniority.currentStatus || '',
        yearsOfExperience: seniority.yearsOfExperience ?? null,
        highestDegree: seniority.highestDegree || '',
        mostSeniorWorkExperience: seniority.mostSeniorWorkExperience || ''
      }
    });
    setChipInputs({});
    setEditingChip(null);
    setEditCareerInputs(true);
    queueProfileSectionFocus('careerInputs');
  };
  const handleCancelCareerInputs = () => {
    setEditCareerInputs(false);
    setCareerInputsDraft(null);
    setChipInputs({});
    setEditingChip(null);
    setCareerInputsError(null);
  };
  const handleChangeCareerInputs = (field, value) => {
    setCareerInputsDraft(prev => ({ ...prev, [field]: value }));
  };
  const handleSaveCareerInputs = async () => {
    setCareerInputsLoading(true);
    setCareerInputsError(null);
    try {
      const draft = careerInputsDraft || {};
      const ui = draft.userIdentity || {};
      if (USER_IDENTITY_FIELDS.some(({ key }) => !String(ui[key] || '').trim())) {
        setCareerInputsError(t('profilePage.errors.identityQuestionsRequired'));
        setCareerInputsLoading(false);
        return;
      }
      const payload = {
        structuredUserInfo: {
          skillDomains: draft.structuredUserInfo?.skillDomains || [],
          skills: draft.structuredUserInfo?.skills || [],
          skillsInDevelopment: draft.structuredUserInfo?.skillsInDevelopment || [],
          keyResponsibilities: draft.structuredUserInfo?.keyResponsibilities || [],
          domains: draft.structuredUserInfo?.domains || []
        },
        userIdentity: {
          workEnjoyMost: draft.userIdentity?.workEnjoyMost || '',
          topicsIndustriesInterest: draft.userIdentity?.topicsIndustriesInterest || '',
          naturallyGoodAt: draft.userIdentity?.naturallyGoodAt || '',
          workEnvironmentFit: draft.userIdentity?.workEnvironmentFit || '',
          workingLifeAchievement: draft.userIdentity?.workingLifeAchievement || ''
        },
        seniority: draft.seniority && typeof draft.seniority === 'object' ? {
          currentStatus: draft.seniority.currentStatus || '',
          yearsOfExperience: draft.seniority.yearsOfExperience ?? null,
          highestDegree: draft.seniority.highestDegree || '',
          mostSeniorWorkExperience: draft.seniority.mostSeniorWorkExperience || ''
        } : undefined
      };

      const res = await axios.put(`/api/profile/career-simulation-inputs?${getProfileApiLangQuery()}`, payload);
      setProfile(prev => ({
        ...prev,
        profile: {
          ...prev.profile,
          careerSimulationInputs: res.data.careerSimulationInputs
        }
      }));
      invalidateProfileCachesAfterMutation();
      setEditCareerInputs(false);
      setCareerInputsDraft(null);
      queueProfileSectionFocus('careerInputs');
    } catch (err) {
      setCareerInputsError(err.response?.data?.error || t('profilePage.errors.saveChangesFailed'));
    } finally {
      setCareerInputsLoading(false);
    }
  };

  // Chip management functions
  const handleAddChip = (field, value) => {
    if (!value.trim()) return;
    
    setCareerInputsDraft(prev => {
      let currentArray;
      let newArray;
      
      if (field === 'structuredUserInfo.domains') {
        currentArray = prev.structuredUserInfo?.domains || [];
        newArray = [...currentArray, value.trim()];
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            domains: newArray
          }
        };
      } else if (field === 'structuredUserInfo.skillDomains') {
        currentArray = prev.structuredUserInfo?.skillDomains || [];
        newArray = [...currentArray, value.trim()];
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            skillDomains: newArray
          }
        };
      } else if (field === 'structuredUserInfo.skills') {
        currentArray = prev.structuredUserInfo?.skills || [];
        newArray = [...currentArray, value.trim()];
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            skills: newArray
          }
        };
      } else if (field === 'structuredUserInfo.skillsInDevelopment') {
        currentArray = prev.structuredUserInfo?.skillsInDevelopment || [];
        newArray = [...currentArray, value.trim()];
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            skillsInDevelopment: newArray
          }
        };
      } else if (field === 'structuredUserInfo.keyResponsibilities') {
        currentArray = prev.structuredUserInfo?.keyResponsibilities || [];
        newArray = [...currentArray, value.trim()];
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            keyResponsibilities: newArray
          }
        };
      } else {
        currentArray = prev[field] || [];
        newArray = [...currentArray, value.trim()];
      }
      
      return { ...prev, [field]: newArray };
    });
    
    // Clear the input
    setChipInputs(prev => ({ ...prev, [field]: '' }));
  };

  const handleDeleteChip = (field, index) => {
    setCareerInputsDraft(prev => {
      if (field === 'structuredUserInfo.domains') {
        const currentArray = prev.structuredUserInfo?.domains || [];
        const newArray = currentArray.filter((_, i) => i !== index);
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            domains: newArray
          }
        };
      } else if (field === 'structuredUserInfo.skillDomains') {
        const currentArray = prev.structuredUserInfo?.skillDomains || [];
        const newArray = currentArray.filter((_, i) => i !== index);
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            skillDomains: newArray
          }
        };
      } else if (field === 'structuredUserInfo.skills') {
        const currentArray = prev.structuredUserInfo?.skills || [];
        const newArray = currentArray.filter((_, i) => i !== index);
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            skills: newArray
          }
        };
      } else if (field === 'structuredUserInfo.skillsInDevelopment') {
        const currentArray = prev.structuredUserInfo?.skillsInDevelopment || [];
        const newArray = currentArray.filter((_, i) => i !== index);
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            skillsInDevelopment: newArray
          }
        };
      } else if (field === 'structuredUserInfo.keyResponsibilities') {
        const currentArray = prev.structuredUserInfo?.keyResponsibilities || [];
        const newArray = currentArray.filter((_, i) => i !== index);
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            keyResponsibilities: newArray
          }
        };
      } else {
        const currentArray = prev[field] || [];
        const newArray = currentArray.filter((_, i) => i !== index);
        return { ...prev, [field]: newArray };
      }
    });
  };

  const handleEditChip = (field, index, newValue) => {
    setCareerInputsDraft(prev => {
      if (field === 'structuredUserInfo.domains') {
        const currentArray = prev.structuredUserInfo?.domains || [];
        const newArray = [...currentArray];
        newArray[index] = newValue;
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            domains: newArray
          }
        };
      } else if (field === 'structuredUserInfo.skillDomains') {
        const currentArray = prev.structuredUserInfo?.skillDomains || [];
        const newArray = [...currentArray];
        newArray[index] = newValue;
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            skillDomains: newArray
          }
        };
      } else if (field === 'structuredUserInfo.skills') {
        const currentArray = prev.structuredUserInfo?.skills || [];
        const newArray = [...currentArray];
        newArray[index] = newValue;
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            skills: newArray
          }
        };
      } else if (field === 'structuredUserInfo.skillsInDevelopment') {
        const currentArray = prev.structuredUserInfo?.skillsInDevelopment || [];
        const newArray = [...currentArray];
        newArray[index] = newValue;
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            skillsInDevelopment: newArray
          }
        };
      } else if (field === 'structuredUserInfo.keyResponsibilities') {
        const currentArray = prev.structuredUserInfo?.keyResponsibilities || [];
        const newArray = [...currentArray];
        newArray[index] = newValue;
        return {
          ...prev,
          structuredUserInfo: {
            ...prev.structuredUserInfo,
            keyResponsibilities: newArray
          }
        };
      } else {
        const currentArray = prev[field] || [];
        const newArray = [...currentArray];
        newArray[index] = newValue;
        
        return { ...prev, [field]: newArray };
      }
    });
    setEditingChip(null);
  };

  const handleChipInputChange = (field, value) => {
    setChipInputs(prev => ({ ...prev, [field]: value }));
  };

  const handleChipInputKeyPress = (field, event) => {
    if (event.key === 'Enter') {
      event.preventDefault();
      handleAddChip(field, chipInputs[field] || '');
    }
  };

  // Helper function to render editable chip sections
  const renderEditableChips = (field, label, placeholder, chipColor = 'primary') => {
    let chips;
    
    if (field === 'structuredUserInfo.domains') {
      chips = careerInputsDraft.structuredUserInfo?.domains || [];
    } else if (field === 'structuredUserInfo.skillDomains') {
      chips = careerInputsDraft.structuredUserInfo?.skillDomains || [];
    } else if (field === 'structuredUserInfo.skills') {
      chips = careerInputsDraft.structuredUserInfo?.skills || [];
    } else if (field === 'structuredUserInfo.skillsInDevelopment') {
      chips = careerInputsDraft.structuredUserInfo?.skillsInDevelopment || [];
    } else if (field === 'structuredUserInfo.keyResponsibilities') {
      chips = careerInputsDraft.structuredUserInfo?.keyResponsibilities || [];
    } else {
      chips = careerInputsDraft[field] || [];
    }
    
    return (
      <Box sx={{ mb: 2 }}>
        {label ? <Typography variant="subtitle2" color="text.secondary">{label}</Typography> : null}
        <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1, mb: 1 }}>
          {chips.map((chip, index) => {
            const chipKey = `${field}-${index}`;
            const isEditing = editingChip === chipKey;
            
            if (isEditing) {
              return (
                <TextField
                  key={chipKey}
                  size="small"
                  autoFocus
                  defaultValue={chipLabelFromGoodAtItem(chip)}
                  onBlur={(e) => handleEditChip(field, index, e.target.value)}
                  onKeyPress={(e) => {
                    if (e.key === 'Enter') {
                      handleEditChip(field, index, e.target.value);
                    } else if (e.key === 'Escape') {
                      setEditingChip(null);
                    }
                  }}
                  sx={{ minWidth: 120 }}
                />
              );
            }
            
            return (
              <Chip
                key={chipKey}
                label={
                  field === 'languages' ? `${chip.language} (${chip.proficiency})` :
                  chipLabelFromGoodAtItem(chip)
                }
                color={chipColor}
                variant="outlined"
                size="small"
                onDelete={() => handleDeleteChip(field, index)}
                onClick={() => setEditingChip(chipKey)}
                sx={{ cursor: 'pointer' }}
              />
            );
          })}
        </Box>
        <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
          <TextField
            size="small"
            placeholder={placeholder}
            value={chipInputs[field] || ''}
            onChange={(e) => handleChipInputChange(field, e.target.value)}
            onKeyPress={(e) => handleChipInputKeyPress(field, e)}
            sx={{ flexGrow: 1 }}
          />
          <Button
            size="small"
            startIcon={<AddIcon />}
            onClick={() => handleAddChip(field, chipInputs[field] || '')}
            disabled={!chipInputs[field]?.trim()}
          >
            Add
          </Button>
        </Box>
      </Box>
    );
  };

  const profilePageActions =
    completion && completion.overall < MIN_PROFILE_COMPLETION_REQUIRED
      ? [
          {
            key: 'complete-profile',
            label: t('profilePagePrompts.incomplete.cta'),
            shortLabel: t('profilePagePrompts.incomplete.ctaShort'),
            href: '/profile/fill?mode=full-update',
            variant: 'contained',
            startIcon: <ArrowForwardIcon />,
          },
        ]
      : [
          {
            key: 'full-profile-update',
            label: t('profilePagePrompts.fullUpdateCta'),
            shortLabel: t('profilePagePrompts.fullUpdateCtaShort'),
            href: '/profile/fill?mode=full-update',
            variant: 'outlined',
            startIcon: <ArrowForwardIcon />,
          },
          ...(completion && completion.overall >= MIN_PROFILE_COMPLETION_REQUIRED
            ? [
                {
                  key: 'go-to-simulation',
                  label: t('profilePagePrompts.goToSimulationCta'),
                  shortLabel: t('profilePagePrompts.goToSimulationCtaShort'),
                  href: goToSimulationHref,
                  variant: 'contained',
                  startIcon: <PuzzlePieceIcon />,
                  nudge: Number(completion?.overall || 0) >= 100,
                },
              ]
            : []),
        ];

  const seniorityDisplayFields = [
    {
      key: 'currentStatus',
      label: t('profilePage.seniority.currentEmploymentStatus'),
      value: formatCurrentEmploymentStatus(seniority.currentStatus),
    },
    {
      key: 'yearsOfExperience',
      label: t('profilePage.seniority.yearsOfWorkExperience'),
      value:
        seniority.yearsOfExperience !== undefined && seniority.yearsOfExperience !== null
          ? String(seniority.yearsOfExperience)
          : '',
    },
    {
      key: 'highestDegree',
      label: t('profilePage.seniority.highestEducationalDegree'),
      value: seniority.highestDegree ? formatHighestDegree(seniority.highestDegree) : '',
    },
    {
      key: 'mostSeniorWorkExperience',
      label: t('profilePage.seniority.mostSeniorWorkExperience'),
      value: formatMostSeniorWorkExperience(seniority.mostSeniorWorkExperience),
    },
  ];

  return (
    <ProfileMobileSnapContext.Provider value={mobileSnapActive}>
    <Box sx={{ maxWidth: 1200, mx: 'auto', p: 3 }}>
      {/* Prompt to complete profile if below threshold */}
      {completion && completion.overall < MIN_PROFILE_COMPLETION_REQUIRED ? (
        <ProfileSnapTarget snap>
          <Typography variant="h4" sx={{ mb: 3, fontWeight: 700, textAlign: 'center' }}>
            {t('profilePagePrompts.incomplete.title')}
          </Typography>
          <Typography variant="body1" sx={{ mb: 4, textAlign: 'center' }}>
            {t('profilePagePrompts.incomplete.description')}
          </Typography>
          <ProfilePageActionBar actions={profilePageActions} />
        </ProfileSnapTarget>
      ) : (
        <ProfileSnapTarget snap>
          <ProfilePageActionBar actions={profilePageActions} />
        </ProfileSnapTarget>
      )}

      <Paper sx={{ p: { xs: 2, sm: 4 }, mb: 4 }} elevation={3}>
        <Grid container spacing={3} alignItems="center">
          <Grid item xs={12} sm={3} md={2}>
            <Box
              sx={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                mx: 'auto',
              }}
            >
              <Avatar
                src={personal.profilePicture ? `/uploads/${personal.profilePicture}?v=${profilePictureKey}` : null}
                alt={profileDisplayName || t('profilePage.photo.alt')}
                sx={{
                  width: 96,
                  height: 96,
                  fontSize: 40,
                  bgcolor: 'primary.main',
                  border: '2px solid',
                  borderColor: 'divider',
                }}
                imgProps={{
                  onError: (e) => {
                    console.error('Failed to load profile picture:', personal.profilePicture);
                    e.target.style.display = 'none';
                  },
                }}
              >
                {(!personal.profilePicture && profileDisplayName) ? profileDisplayName[0].toUpperCase() : (!personal.profilePicture && <PersonIcon fontSize="large" />)}
              </Avatar>
              <Tooltip
                title={
                  personal.profilePicture
                    ? t('profilePage.photo.edit')
                    : t('profilePage.photo.add')
                }
              >
                <IconButton
                  size="small"
                  onClick={() => setProfilePictureDialogOpen(true)}
                  aria-label={
                    personal.profilePicture
                      ? t('profilePage.photo.edit')
                      : t('profilePage.photo.add')
                  }
                  sx={{ mt: 0.5 }}
                >
                  {personal.profilePicture ? <EditIcon /> : <AddIcon />}
                </IconButton>
              </Tooltip>
            </Box>
          </Grid>
          <Grid item xs={12} sm={9} md={10}>
            <Box
              sx={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                gap: 2,
                flexWrap: 'wrap',
                width: '100%',
              }}
            >
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap', minWidth: 0 }}>
                <Typography variant="h4" component="h1" sx={{ fontWeight: 700 }}>
                  {profileDisplayName || t('profilePage.nameEditor.placeholderName')}
                </Typography>
                <Tooltip title={t('profilePage.nameEditor.editCta')}>
                  <IconButton
                    size="small"
                    onClick={handleStartEditProfileName}
                    aria-label={t('profilePage.nameEditor.editCta')}
                  >
                    <EditIcon />
                  </IconButton>
                </Tooltip>
              </Box>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' }}>
                {profileCompletionHeader}
                {showLoginSecuritySection && (
                  <Button
                    variant="outlined"
                    size="small"
                    startIcon={<LockIcon />}
                    onClick={openLoginSecurityDialog}
                  >
                    {t('profilePage.loginSecurity.title')}
                  </Button>
                )}
              </Box>
            </Box>
          </Grid>
        </Grid>
      </Paper>

      {/* Who are you? (five identity prompts → embedding text) */}
      <Paper ref={userIdentitySectionRef} sx={{ p: { xs: 2, sm: 3 }, mb: 4, ...profileSectionScrollMarginSx }} elevation={1}>
        <ProfileSnapTarget snap>
          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            <PsychologyIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
            {t('profilePage.sections.identity')}
          </Typography>
        </ProfileSnapTarget>
        {editSection === 'userIdentity' ? (
          <UserIdentityTextForm
            initialData={editFormData}
            loading={formLoading}
            error={formError}
            onCancel={handleCancel}
            onSubmit={data => handleSaveUserIdentity(data)}
          />
        ) : (
          <>
            {USER_IDENTITY_FIELDS.map(({ key, questionKey }, idx) => (
              <ProfileSnapTarget key={key} snap={idx > 0}>
                <Box sx={{ mt: 2, mb: 1 }}>
                  <Typography
                    variant="body1"
                    sx={{
                      color: '#950202',
                      fontWeight: 600,
                      mb: 1.5,
                    }}
                  >
                    {t(questionKey)}
                  </Typography>
                  <Typography variant="body1" sx={{ whiteSpace: 'pre-wrap' }}>
                    {whoAreYouDisplayLines[idx]}
                  </Typography>
                </Box>
                {idx < 4 ? <Divider sx={{ my: 3 }} /> : null}
              </ProfileSnapTarget>
            ))}
            <Button
              variant="outlined"
              size="small"
              startIcon={<EditIcon />}
              onClick={handleEditUserIdentity}
              sx={{ mt: 1 }}
            >
              {t('profilePage.actions.edit')}
            </Button>
          </>
        )}
      </Paper>

      {/* What are you good at? */}
      <Paper ref={structuredInfoSectionRef} sx={{ p: { xs: 2, sm: 3 }, mb: 4, ...profileSectionScrollMarginSx }} elevation={1}>
        <ProfileSnapTarget snap>
          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            <AccountTreeIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
            {t('profilePage.sections.goodAt')}
          </Typography>
        </ProfileSnapTarget>
        {editStructuredInfo ? (
          <>
            {structuredInfoError && (
              <Alert severity="error" sx={{ mb: 2 }}>
                {structuredInfoError}
              </Alert>
            )}
            <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 2 }}>
              {t('profilePage.structuredInfo.maxEntriesPerCategory', { max: MAX_GOOD_AT_PER_CATEGORY })}
            </Typography>
            {[
              {
                key: 'skillDomains',
                title: t('profilePage.structuredInfo.strengths.title'),
                addLabel: t('profilePage.structuredInfo.strengths.addCta'),
                helper: t('profilePage.structuredInfo.strengths.helper'),
                multiline: false,
              },
              {
                key: 'domains',
                title: t('profilePage.structuredInfo.industrySectors.title'),
                addLabel: t('profilePage.structuredInfo.industrySectors.addCta'),
                helper: t('profilePage.structuredInfo.industrySectors.helper'),
                multiline: false,
              },
              {
                key: 'keyResponsibilities',
                title: t('profilePage.structuredInfo.responsibilities.title'),
                addLabel: t('profilePage.structuredInfo.responsibilities.addCta'),
                helper: t('profilePage.structuredInfo.responsibilities.helper'),
                multiline: true,
                minRows: 3,
              },
              {
                key: 'skills',
                title: t('profilePage.structuredInfo.skills.title'),
                addLabel: t('profilePage.structuredInfo.skills.addCta'),
                helper: t('profilePage.structuredInfo.skills.helper'),
                multiline: false,
              },
              {
                key: 'skillsInDevelopment',
                title: t('profilePage.structuredInfo.learningGoals.title'),
                addLabel: t('profilePage.structuredInfo.learningGoals.addCta'),
                helper: t('profilePage.structuredInfo.learningGoals.helper'),
                multiline: false,
              },
            ].map(({ key, title, addLabel, helper, multiline, minRows = 1 }, sectionIdx) => {
              const values = structuredInfoDraft[key] || [];
              return (
                <React.Fragment key={key}>
                <Box sx={{ mb: 2.5 }}>
                  <Typography variant="body1" sx={{ color: '#950202', fontWeight: 600, mb: 1.5 }}>
                    {title}
                  </Typography>
                  <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 1 }}>
                    {helper}
                  </Typography>
                  {values.length === 0 && (
                    <Typography variant="body2" color="text.secondary" sx={{ fontStyle: 'italic', mb: 1 }}>
                      {t('profilePage.structuredInfo.emptyEntries')}
                    </Typography>
                  )}
                  {values.map((value, idx) => (
                    <Box key={`${key}-${idx}`} sx={{ display: 'flex', alignItems: 'flex-start', gap: 1, mb: 1 }}>
                      <TextField
                        fullWidth
                        value={value}
                        onChange={(e) => handleStructuredInfoItemChange(key, idx, e.target.value)}
                        multiline={multiline}
                        minRows={multiline ? minRows : undefined}
                        placeholder={`${title} ${idx + 1}`}
                      />
                      <IconButton
                        aria-label={`Remove ${title} ${idx + 1}`}
                        onClick={() => handleStructuredInfoItemRemove(key, idx)}
                        sx={{ mt: multiline ? 0.5 : 0 }}
                      >
                        <DeleteIcon />
                      </IconButton>
                    </Box>
                  ))}
                  <Button
                    size="small"
                    variant="outlined"
                    startIcon={<AddIcon />}
                    onClick={() => handleStructuredInfoItemAdd(key)}
                    disabled={values.length >= MAX_GOOD_AT_PER_CATEGORY}
                  >
                    {addLabel}
                  </Button>
                </Box>
                {sectionIdx < 4 ? <Divider sx={{ my: 3 }} /> : null}
                </React.Fragment>
              );
            })}
            <Box
              sx={{
                mt: 1,
                display: 'flex',
                flexWrap: 'wrap',
                alignItems: 'center',
                justifyContent: 'flex-start',
                gap: 1,
              }}
            >
              <Button
                variant="outlined"
                size="small"
                startIcon={<SaveIcon />}
                onClick={handleSaveStructuredInfo}
                disabled={structuredInfoLoading}
              >
                {t('profilePage.actions.save')}
              </Button>
              <Button
                variant="outlined"
                color="error"
                size="small"
                startIcon={<CancelIcon />}
                onClick={handleCancelStructuredInfo}
                disabled={structuredInfoLoading}
              >
                {t('profilePage.actions.cancel')}
              </Button>
            </Box>
          </>
        ) : (
          <>
            {[
              {
                key: 'strengths',
                title: t('profilePage.structuredInfo.strengths.title'),
                empty: t('profilePage.structuredInfo.strengths.empty'),
                content: strengthSkillDomains.length > 0 ? (
                  <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                    {strengthSkillDomains.map((domain, idx) => (
                      <Chip
                        key={idx}
                        label={chipLabelFromGoodAtItem(domain)}
                        color="default"
                        variant="outlined"
                        sx={goodAtReadonlyChipSx}
                      />
                    ))}
                  </Box>
                ) : (
                  <Typography variant="body1" color="text.disabled" sx={{ fontStyle: 'italic' }}>
                    {t('profilePage.structuredInfo.strengths.empty')}
                  </Typography>
                ),
              },
              {
                key: 'industrySectors',
                title: t('profilePage.structuredInfo.industrySectors.title'),
                content: structuredDomains.length > 0 ? (
                  <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                    {structuredDomains.map((domain, idx) => (
                      <Chip
                        key={idx}
                        label={chipLabelFromGoodAtItem(domain)}
                        color="success"
                        variant="outlined"
                        sx={goodAtReadonlyChipSx}
                      />
                    ))}
                  </Box>
                ) : (
                  <Typography variant="body1" color="text.disabled" sx={{ fontStyle: 'italic' }}>
                    {t('profilePage.structuredInfo.industrySectors.empty')}
                  </Typography>
                ),
              },
              {
                key: 'responsibilities',
                title: t('profilePage.structuredInfo.responsibilities.title'),
                content: structuredKeyResponsibilities.length > 0 ? (
                  <Box component="ul" sx={{ pl: 2, m: 0 }}>
                    {structuredKeyResponsibilities.map((responsibility, idx) => (
                      <Typography key={idx} component="li" variant="body1" color="text.primary">
                        {chipLabelFromGoodAtItem(responsibility)}
                      </Typography>
                    ))}
                  </Box>
                ) : (
                  <Typography variant="body1" color="text.disabled" sx={{ fontStyle: 'italic' }}>
                    {t('profilePage.structuredInfo.responsibilities.empty')}
                  </Typography>
                ),
              },
              {
                key: 'skills',
                title: t('profilePage.structuredInfo.skills.title'),
                content: structuredSkills.length > 0 ? (
                  <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                    {structuredSkills.map((skill, idx) => (
                      <Chip
                        key={idx}
                        label={chipLabelFromGoodAtItem(skill)}
                        color="primary"
                        variant="outlined"
                        sx={goodAtReadonlyChipSx}
                      />
                    ))}
                  </Box>
                ) : (
                  <Typography variant="body1" color="text.disabled" sx={{ fontStyle: 'italic' }}>
                    {t('profilePage.structuredInfo.skills.empty')}
                  </Typography>
                ),
              },
              {
                key: 'learningGoals',
                title: t('profilePage.structuredInfo.learningGoals.title'),
                content: structuredSkillsInDevelopment.length > 0 ? (
                  <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                    {structuredSkillsInDevelopment.map((skill, idx) => (
                      <Chip
                        key={idx}
                        label={chipLabelFromGoodAtItem(skill)}
                        color="info"
                        variant="outlined"
                        sx={goodAtReadonlyChipSx}
                      />
                    ))}
                  </Box>
                ) : (
                  <Typography variant="body1" color="text.disabled" sx={{ fontStyle: 'italic' }}>
                    {t('profilePage.structuredInfo.learningGoals.empty')}
                  </Typography>
                ),
              },
            ].map(({ key, title, content }, sectionIdx) => (
              <ProfileSnapTarget key={key} snap={sectionIdx > 0}>
                <Box sx={{ mt: 2, mb: 1 }}>
                  <Typography variant="body1" sx={{ color: '#950202', fontWeight: 600, mb: 1.5 }}>
                    {title}
                  </Typography>
                  {content}
                </Box>
                {sectionIdx < 4 ? <Divider sx={{ my: 3 }} /> : null}
              </ProfileSnapTarget>
            ))}
            <Button
              variant="outlined"
              size="small"
              startIcon={<EditIcon />}
              onClick={handleEditStructuredInfo}
              sx={{ mt: 1 }}
            >
              {t('profilePage.actions.edit')}
            </Button>
          </>
        )}
      </Paper>

      {/* How experienced are you? (seniority data) */}
      <Paper ref={senioritySectionRef} sx={{ p: { xs: 2, sm: 3 }, mb: 4, ...profileSectionScrollMarginSx }} elevation={1}>
        <ProfileSnapTarget snap>
          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            <WorkHistoryIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
            {t('profilePage.sections.experience')}
          </Typography>
        </ProfileSnapTarget>
        {editSection === 'seniority' ? (
          <SeniorityForm
            initialData={editFormData}
            loading={formLoading}
            error={formError}
            onCancel={handleCancel}
            onSubmit={data => handleSaveSeniority(data)}
          />
        ) : (
          <>
            {seniorityDisplayFields.map((field) => (
              <React.Fragment key={field.key}>
                {renderField(
                  field.label,
                  field.value,
                  false,
                  '',
                  { xs: 12, sm: 5, md: 4 },
                  { xs: 12, sm: 7, md: 8 }
                )}
              </React.Fragment>
            ))}
            <Button
              variant="outlined"
              size="small"
              startIcon={<EditIcon />}
              onClick={handleEditSeniority}
              sx={{ mt: 1 }}
            >
              {t('profilePage.actions.edit')}
            </Button>
          </>
        )}
      </Paper>

      {/* Career Simulation Inputs */}
      {showCareerSimulationInputs && profile?.profile?.careerSimulationInputs && (
        <Paper ref={careerInputsSectionRef} sx={{ p: { xs: 2, sm: 3 }, mb: 4, ...profileSectionScrollMarginSx }} elevation={1}>
          <ProfileSnapTarget snap>
            <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
              <PuzzlePieceIcon color="primary" sx={{ mr: 1 }} />
              <Typography variant="h6">{t('profilePage.careerInputs.title')}</Typography>
            </Box>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
              {t('profilePage.careerInputs.description')}
              <br />
              <strong>{t('profilePage.careerInputs.tipLabel')}</strong> {t('profilePage.careerInputs.tipDescription')}
            </Typography>
            {!editCareerInputs && (
              <Box sx={{ display: 'flex', gap: 1, mt: 1, mb: 2 }}>
                <Button
                  variant="outlined"
                  startIcon={<EditIcon />}
                  onClick={handleEditCareerInputs}
                >
                  Edit
                </Button>
              </Box>
            )}
          </ProfileSnapTarget>
          {careerInputsError && <Alert severity="error" sx={{ mb: 2 }}>{careerInputsError}</Alert>}
          {!editCareerInputs && (
            <ProfileSnapTarget snap={false}>
              <Box sx={{ mb: 2 }}>
                <Typography variant="subtitle2" color="text.secondary" sx={{ mb: 0.5 }}>
                  {t('profilePage.careerInputs.embeddingIdentityLabel')}
                </Typography>
                <Typography
                  variant="body2"
                  color={careerInputsIdentityEmbeddingText ? 'text.primary' : 'text.disabled'}
                  sx={{ whiteSpace: 'pre-wrap' }}
                >
                  {careerInputsIdentityEmbeddingText || <span style={{ fontStyle: 'italic' }}>{t('profilePage.careerInputs.notAvailableYet')}</span>}
                </Typography>
              </Box>
            </ProfileSnapTarget>
          )}
          {editCareerInputs ? (
            <Box>
              {/* What are you good at? */}
              <Box sx={{ mb: 2 }}>
                <Typography variant="subtitle2" color="text.secondary" sx={{ mb: 1 }}>{t('profilePage.sections.goodAt')}</Typography>
                {renderEditableChips(
                  'structuredUserInfo.skillDomains',
                  t('profilePage.structuredInfo.strengths.title'),
                  t('profilePage.careerInputs.editablePlaceholders.strengths'),
                  'default'
                )}
                {renderEditableChips(
                  'structuredUserInfo.domains',
                  t('profilePage.structuredInfo.industrySectors.title'),
                  t('profilePage.careerInputs.editablePlaceholders.industrySectors'),
                  'success'
                )}
              </Box>
              {renderEditableChips('structuredUserInfo.keyResponsibilities', t('profilePage.structuredInfo.responsibilities.title'), t('profilePage.careerInputs.editablePlaceholders.responsibilities'), 'secondary')}
              {renderEditableChips('structuredUserInfo.skills', t('profilePage.structuredInfo.skills.title'), t('profilePage.careerInputs.editablePlaceholders.skills'), 'primary')}
              {renderEditableChips('structuredUserInfo.skillsInDevelopment', t('profilePage.structuredInfo.learningGoals.title'), t('profilePage.careerInputs.editablePlaceholders.learningGoals'), 'secondary')}

              {/* Experience / seniority sub-vector (career simulation inputs) */}
              <Box sx={{ mb: 2 }}>
                <Typography variant="subtitle2" color="text.secondary" sx={{ mb: 1 }}>{t('profilePage.sections.experience')}</Typography>
                <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                  <TextField
                    select
                    label={t('profilePage.seniority.currentEmploymentStatus')}
                    size="small"
                    value={careerInputsDraft.seniority?.currentStatus || ''}
                    onChange={e => handleChangeCareerInputs('seniority', { ...careerInputsDraft.seniority, currentStatus: e.target.value })}
                    sx={{ minWidth: 140 }}
                  >
                    <MenuItem value="">—</MenuItem>
                    {CURRENT_EMPLOYMENT_STATUS_OPTIONS.map((opt) => (
                      <MenuItem key={opt.value} value={opt.value}>
                        {opt.label}
                      </MenuItem>
                    ))}
                  </TextField>
                  <TextField
                    type="number"
                    label="Years of Experience"
                    size="small"
                    value={careerInputsDraft.seniority?.yearsOfExperience ?? ''}
                    onChange={e => handleChangeCareerInputs('seniority', { ...careerInputsDraft.seniority, yearsOfExperience: e.target.value === '' ? null : Number(e.target.value) })}
                    inputProps={{ min: 0, max: 50 }}
                    sx={{ minWidth: 120 }}
                  />
                  <TextField
                    select
                    label="Highest Degree"
                    size="small"
                    value={careerInputsDraft.seniority?.highestDegree || ''}
                    onChange={e => handleChangeCareerInputs('seniority', { ...careerInputsDraft.seniority, highestDegree: e.target.value })}
                    sx={{ minWidth: 140 }}
                  >
                    <MenuItem value="">—</MenuItem>
                    {HIGHEST_DEGREE_OPTIONS.map((opt) => (
                      <MenuItem key={opt.value} value={opt.value}>
                        {formatHighestDegree(opt.value)}
                      </MenuItem>
                    ))}
                  </TextField>
                  <TextField
                    select
                    label="Most Senior Role"
                    size="small"
                    value={careerInputsDraft.seniority?.mostSeniorWorkExperience || ''}
                    onChange={e => handleChangeCareerInputs('seniority', { ...careerInputsDraft.seniority, mostSeniorWorkExperience: e.target.value })}
                    sx={{ minWidth: 140 }}
                  >
                    <MenuItem value="">—</MenuItem>
                    <MenuItem value="intern">Intern</MenuItem>
                    <MenuItem value="entry_level">Entry level</MenuItem>
                    <MenuItem value="mid_level">Mid-level</MenuItem>
                    <MenuItem value="senior">Senior</MenuItem>
                    <MenuItem value="lead">Lead</MenuItem>
                    <MenuItem value="manager">Manager</MenuItem>
                    <MenuItem value="director">Director</MenuItem>
                    <MenuItem value="vp">VP</MenuItem>
                    <MenuItem value="c_suite">C-Suite</MenuItem>
                  </TextField>
                </Box>
              </Box>

              <Box sx={{ display: 'flex', gap: 2, mt: 2 }}>
                <Button variant="contained" color="primary" onClick={handleSaveCareerInputs} disabled={careerInputsLoading}>{t('profilePage.actions.save')}</Button>
                <Button variant="outlined" onClick={handleCancelCareerInputs} disabled={careerInputsLoading}>{t('profilePage.actions.cancel')}</Button>
              </Box>
            </Box>
          ) : (
            <>
              {[
                {
                  key: 'strengths',
                  snap: true,
                  title: t('profilePage.careerInputs.strengthsLabel'),
                  content: (() => {
                    const csiStructured = profile.profile.careerSimulationInputs?.structuredUserInfo || {};
                    const strengthChips = getRawItems(csiStructured.skillDomains);
                    if (strengthChips.length === 0) {
                      return (
                        <Typography variant="body2" color="text.disabled" sx={{ fontStyle: 'italic' }}>
                          {t('profilePage.careerInputs.empty.strengths')}
                        </Typography>
                      );
                    }
                    return (
                      <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                        {strengthChips.map((label, idx) => (
                          <Chip key={idx} label={chipLabelFromGoodAtItem(label)} size="small" color="default" variant="outlined" />
                        ))}
                      </Box>
                    );
                  })(),
                },
                {
                  key: 'occupationGroup',
                  snap: true,
                  title: t('profilePage.careerInputs.occupationGroupLabel'),
                  content: (() => {
                    const s = profile.profile.careerSimulationInputs.structuredUserInfo || {};
                    const csiDomains = getRawItems(s.domains);
                    if (csiDomains.length === 0) {
                      return (
                        <Typography variant="body2" color="text.disabled" sx={{ fontStyle: 'italic' }}>
                          {t('profilePage.careerInputs.empty.industrySectors')}
                        </Typography>
                      );
                    }
                    return (
                      <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                        {csiDomains.map((domain, idx) => (
                          <Chip key={`domain-${idx}`} label={chipLabelFromGoodAtItem(domain)} size="small" color="success" variant="outlined" />
                        ))}
                      </Box>
                    );
                  })(),
                },
                {
                  key: 'responsibilities',
                  snap: true,
                  title: t('profilePage.careerInputs.responsibilitiesLabel'),
                  content: getRawItems(profile.profile.careerSimulationInputs.structuredUserInfo?.keyResponsibilities).length > 0 ? (
                    <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                      {getRawItems(profile.profile.careerSimulationInputs.structuredUserInfo?.keyResponsibilities).map((resp, respIdx) => (
                        <Chip key={respIdx} label={resp} size="small" variant="outlined" />
                      ))}
                    </Box>
                  ) : (
                    <Typography variant="body2" color="text.disabled" sx={{ fontStyle: 'italic' }}>
                      {t('profilePage.careerInputs.empty.responsibilities')}
                    </Typography>
                  ),
                },
                {
                  key: 'skills',
                  snap: true,
                  title: t('profilePage.careerInputs.requiredSkillsLabel'),
                  content: getRawItems(profile.profile.careerSimulationInputs.structuredUserInfo?.skills).length > 0 ? (
                    <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                      {getRawItems(profile.profile.careerSimulationInputs.structuredUserInfo?.skills).map((skill, idx) => (
                        <Chip key={idx} label={chipLabelFromGoodAtItem(skill)} size="small" color="primary" variant="outlined" />
                      ))}
                    </Box>
                  ) : (
                    <Typography variant="body2" color="text.disabled" sx={{ fontStyle: 'italic' }}>
                      {t('profilePage.careerInputs.empty.skills')}
                    </Typography>
                  ),
                },
                {
                  key: 'learningGoals',
                  snap: true,
                  title: t('profilePage.careerInputs.skillsInDevelopmentLabel'),
                  content: getRawItems(profile.profile.careerSimulationInputs.structuredUserInfo?.skillsInDevelopment).length > 0 ? (
                    <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                      {getRawItems(profile.profile.careerSimulationInputs.structuredUserInfo?.skillsInDevelopment).map((skill, idx) => (
                        <Chip key={idx} label={chipLabelFromGoodAtItem(skill)} size="small" color="secondary" variant="outlined" />
                      ))}
                    </Box>
                  ) : (
                    <Typography variant="body2" color="text.disabled" sx={{ fontStyle: 'italic' }}>
                      {t('profilePage.careerInputs.empty.learningGoals')}
                    </Typography>
                  ),
                },
                {
                  key: 'optionalSkills',
                  snap: true,
                  title: t('profilePage.careerInputs.optionalSkillsLabel'),
                  content: (() => {
                    const required = getRawItems(profile.profile.careerSimulationInputs.structuredUserInfo?.skills);
                    const learning = getRawItems(profile.profile.careerSimulationInputs.structuredUserInfo?.skillsInDevelopment);
                    const merged = [...new Set(
                      [...required, ...learning]
                        .map((v) => normalizeStructuredListItemLabel(v, currentLang))
                        .filter(Boolean)
                    )];
                    if (merged.length === 0) {
                      return (
                        <Typography variant="body2" color="text.disabled" sx={{ fontStyle: 'italic' }}>
                          {t('profilePage.careerInputs.empty.optionalSkills')}
                        </Typography>
                      );
                    }
                    return (
                      <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                        {merged.map((skill, idx) => (
                          <Chip key={`optional-skill-${idx}`} label={chipLabelFromGoodAtItem(skill)} size="small" color="secondary" variant="outlined" />
                        ))}
                      </Box>
                    );
                  })(),
                },
                {
                  key: 'seniority',
                  snap: true,
                  title: t('profilePage.careerInputs.seniorityLabel'),
                  titleSx: { mb: 1 },
                  content: (() => {
                    const s = profile.profile.careerSimulationInputs.seniority;
                    const hasAny = s && (s.currentStatus || s.yearsOfExperience != null || s.highestDegree || s.mostSeniorWorkExperience);
                    if (!hasAny) {
                      return (
                        <Typography variant="body2" color="text.disabled" sx={{ fontStyle: 'italic' }}>
                          {t('profilePage.careerInputs.empty.experience')}
                        </Typography>
                      );
                    }
                    const parts = [];
                    if (s.currentStatus) parts.push(formatCurrentEmploymentStatus(s.currentStatus));
                    if (s.yearsOfExperience != null) parts.push(t('profilePage.seniority.yearsValue', { count: s.yearsOfExperience }));
                    if (s.highestDegree) parts.push(formatHighestDegree(s.highestDegree));
                    if (s.mostSeniorWorkExperience) parts.push(formatMostSeniorWorkExperience(s.mostSeniorWorkExperience));
                    return (
                      <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                        {parts.map((p, i) => (
                          <Chip key={i} label={p} size="small" variant="outlined" />
                        ))}
                      </Box>
                    );
                  })(),
                },
              ].map(({ key, snap, title, content, titleSx }) => (
                <ProfileSnapTarget key={key} snap={snap}>
                  <Box sx={{ mb: 2 }}>
                    <Typography variant="subtitle2" color="text.secondary" sx={{ mb: 0.5, ...titleSx }}>
                      {title}
                    </Typography>
                    {content}
                  </Box>
                </ProfileSnapTarget>
              ))}
              {profile.profile.careerSimulationInputs.lastManualEdit && (
                <Typography variant="caption" color="text.disabled">
                  {t('profilePage.careerInputs.lastManuallyEdited', { date: new Date(profile.profile.careerSimulationInputs.lastManualEdit).toLocaleString() })}
                </Typography>
              )}
              {profile.profile.careerSimulationInputs.lastCalculated && (
                <Typography variant="caption" color="text.disabled">
                  {t('profilePage.careerInputs.lastAutoCalculated', { date: new Date(profile.profile.careerSimulationInputs.lastCalculated).toLocaleString() })}
                </Typography>
              )}
            </>
          )}
        </Paper>
      )}

      {/* Documents */}
      <Paper
        sx={{ p: { xs: 2, sm: 3 }, mb: 4, width: '100%', maxWidth: '100%', overflow: 'hidden' }}
        elevation={1}
      >
        <ProfileSnapTarget snap>
          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            <DescriptionIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
            {t('profilePage.documents.title')}
          </Typography>
        </ProfileSnapTarget>
        {cvReviewError && (
          <Alert severity="error" sx={{ mb: 2 }} onClose={() => setCvReviewError(null)}>
            {cvReviewError}
          </Alert>
        )}
        <ProfileDocumentList
          documents={documents ? documents.map((doc) => ({ ...doc, id: doc.id || doc._id })) : []}
          onDocumentsUpdate={handleDocumentsUpdate}
          disabled={loading || savingCvReview}
          onOpenReview={(docId) => setDocumentReviewDocId(String(docId))}
        />
      </Paper>

      {documentReviewDocId && (
        <Suspense fallback={null}>
          <DocumentUploadForm
            enableExtractionReview
            hideDocumentList
            openReviewForDocumentId={documentReviewDocId}
            restrictAutoResumeToDocumentId={documentReviewDocId}
            documents={documents ? documents.map((doc) => ({ ...doc, id: doc.id || doc._id })) : []}
            onDocumentsUpdate={handleDocumentsUpdate}
            onExtractedProfileReview={handleExtractedProfileReview}
            onReviewSessionEnd={() => setDocumentReviewDocId(null)}
            loading={loading}
            parentSavingReview={savingCvReview}
            showSectionTitle={false}
            showUploadControls={false}
            reviewSaveMode="merge"
          />
        </Suspense>
      )}

      {showLoginSecuritySection && (
        <Dialog
          open={loginSecurityDialogOpen}
          onClose={() => setLoginSecurityDialogOpen(false)}
          maxWidth="sm"
          fullWidth
          scroll="paper"
        >
          <DialogTitle sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <LockIcon color="primary" />
            {t('profilePage.loginSecurity.title')}
          </DialogTitle>
          <DialogContent dividers>
            <LoginSecuritySection
              layout="dialog"
              loginSecurity={loginSecurity.data}
              loading={loginSecurity.loading}
              error={loginSecurity.error}
              onRefresh={fetchLoginSecurity}
            />
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setLoginSecurityDialogOpen(false)}>{t('profilePage.actions.close')}</Button>
          </DialogActions>
        </Dialog>
      )}

      <Dialog
        open={profileNameDialogOpen}
        onClose={handleCancelEditProfileName}
        maxWidth="sm"
        fullWidth
        aria-labelledby="profile-name-dialog-title"
      >
        <DialogTitle id="profile-name-dialog-title">{t('profilePage.nameEditor.editCta')}</DialogTitle>
        <DialogContent>
          <TextField
            autoFocus
            margin="dense"
            label={t('profilePage.nameEditor.label')}
            fullWidth
            variant="outlined"
            value={profileNameDraft}
            onChange={(e) => {
              setProfileNameDraft(e.target.value);
              if (profileNameError) setProfileNameError(null);
            }}
            error={!!profileNameError}
            helperText={profileNameError || t('profilePage.nameEditor.helper')}
            disabled={profileNameLoading}
            sx={{ mb: 2 }}
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCancelEditProfileName} disabled={profileNameLoading}>
            {t('profilePage.actions.cancel')}
          </Button>
          <Button
            onClick={handleSaveProfileName}
            variant="contained"
            color="primary"
            disabled={!profileNameDraft.trim() || profileNameLoading}
          >
            {t('profilePage.actions.save')}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Profile Picture Editor Dialog */}
      <ProfilePictureEditor
        open={profilePictureDialogOpen}
        onClose={() => setProfilePictureDialogOpen(false)}
        currentPicture={personal.profilePicture}
        onPictureUpdate={async (newPicture) => {
          // Close dialog first
          setProfilePictureDialogOpen(false);
          
          // Update cache key to force image reload
          setProfilePictureKey(prev => prev + 1);
          
          // Update profile state immediately with new picture
          setProfile(prev => ({
            ...prev,
            profile: {
              ...prev.profile,
              personalInfo: {
                ...prev.profile.personalInfo,
                profilePicture: newPicture
              }
            }
          }));

          await fetchProfile({ force: true });
          setProfilePictureKey(prev => prev + 1);
        }}
      />
    </Box>
    </ProfileMobileSnapContext.Provider>
  );
};

export default Profile; 