/** In-process CV extraction pipeline events (fan-out after heuristics). */

const CV_HEURISTICS_COMPLETED = 'CV_HEURISTICS_COMPLETED';
const CV_IDENTITY_COMPLETED = 'CV_IDENTITY_COMPLETED';
const CV_STRUCTURED_COMPLETED = 'CV_STRUCTURED_COMPLETED';
const CV_NARRATIVE_COMPLETED = 'CV_NARRATIVE_COMPLETED';

module.exports = {
  CV_HEURISTICS_COMPLETED,
  CV_IDENTITY_COMPLETED,
  CV_STRUCTURED_COMPLETED,
  CV_NARRATIVE_COMPLETED,
};
