jest.mock('../services/jobAnalysis/roleIdentityComposer', () => ({
  openaiProvider: jest.fn(async () => JSON.stringify({ user_identity_text: 'generated by llm' })),
}));

const { openaiProvider } = require('../services/jobAnalysis/roleIdentityComposer');
const {
  resolveUserIdentityEmbeddingText,
} = require('../services/embedding/userIdentityEmbeddingTextService');

describe('userIdentityEmbeddingTextService precedence', () => {
  test('uses who_are_you identityEmbeddingText before cached embedding text/generation', async () => {
    const text = await resolveUserIdentityEmbeddingText({
      identityEmbeddingText: 'I build healthcare data products with clear user value and pragmatic execution.',
      embeddingOptimizedUserIdentityText: 'cached legacy embedding text',
      embeddingUserIdentitySourceFingerprint: 'some-old-fingerprint',
      userIdentityAnswers: {
        workEnjoyMost: 'Building useful products',
        topicsIndustriesInterest: 'Healthcare',
        naturallyGoodAt: 'Structuring ambiguity',
        workEnvironmentFit: 'Collaborative teams',
        workingLifeAchievement: 'Improve patient outcomes',
      },
    });

    expect(text).toBe('I build healthcare data products with clear user value and pragmatic execution.');
    expect(openaiProvider).not.toHaveBeenCalled();
  });
});
